name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: npm ci
    - run: npm run build
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name webxqodmsj6q5ckm  --auth-mode key -d '$web' -s "./build"
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "cdnxqodmsj6q5ckm" --name "endpointxqodmsj6q5ckm" --resource-group "pergus-bicep"
    # Azure logout
    - name: logout
      run: |
            az logout
      if: always()